version: "3"

vars:
  BINARY_DIR: ./
  BINARY_NAME: man-mcp
  PACKAGE: "github.com/killi1812/man-mcp"

tasks:
  default:
    cmds:
      - task: list-tools
    silent: false

  dev:
    description: build project binary for development
    vars:
      BUILD: "dev"
    cmds:
      - task: build
        vars:
          BUILD: "{{.BUILD}}"
    silent: true

  build:
    description: build project binary
    dir: src
    vars:
      VERSION:
        sh: git describe --tags --always --abbrev=0 --match='v[0-9]*.[0-9]*.[0-9]*' 2> /dev/null | sed 's/^.//' || echo "0.0.0"
      COMMIT_HASH:
        sh: git rev-parse --short HEAD 2> /dev/null || echo "n/a"
      BUILD_TIMESTAMP:
        sh: date '+%Y-%m-%dT%H:%M:%S'
      LDFLAGS: "-X '{{.PACKAGE}}/app.Build={{.BUILD}}' -X '{{.PACKAGE}}/app.Version={{.VERSION}}' -X '{{.PACKAGE}}/app.CommitHash={{.COMMIT_HASH}}' -X '{{.PACKAGE}}/app.BuildTimestamp={{.BUILD_TIMESTAMP}}'"
    cmds:
      - cmd: "echo 'Build info\n\tBuild:\t\t{{.BUILD}}\n\tVersion:\t{{.VERSION}}\n\tCommit:\t\t{{.COMMIT_HASH}}\n\tTime Stamp:\t{{.BUILD_TIMESTAMP}}'"
      - cmd: mkdir -p {{.ROOT_DIR}}/{{.BINARY_DIR}}
      - cmd: go build -ldflags="{{.LDFLAGS}}" -o {{.ROOT_DIR}}/{{.BINARY_DIR}}/{{.BINARY_NAME}} .
    silent: true

  clean:
    description: remove build artifacts and test files
    cmds:
      - rm -f {{.ROOT_DIR}}/{{.BINARY_NAME}}
      - rm -rf {{.ROOT_DIR}}/bin/
      - rm -f {{.ROOT_DIR}}/src/coverage.*
      - rm -f {{.ROOT_DIR}}/coverage.*
    silent: false

  install:
    description: install project as your local binary
    vars:
      BUILD: "prod"
      INSTALL_DIR:
        sh: echo "${GOBIN:-$HOME/.local/bin}"
    cmds:
      - task: build
        vars:
          BUILD: "{{.BUILD}}"
      - mkdir -p {{.INSTALL_DIR}}
      - cp {{.ROOT_DIR}}/{{.BINARY_DIR}}/{{.BINARY_NAME}} {{.INSTALL_DIR}}/{{.BINARY_NAME}}
      - echo "Installed {{.BINARY_NAME}} to {{.INSTALL_DIR}}/{{.BINARY_NAME}}"
    silent: false

  test:
    description: run project tests
    dir: src
    cmds:
      - go test -v ./...
    silent: false

  coverage:
    description: creates project coverage file
    dir: src
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -func=coverage.out
    silent: false

  list-tools:
    cmds:
      - go version
      - gcc --version
      - task --version
    silent: true
